baseURL = 'https://cgflashfic.netlify.app/'

languageCode = 'en-us'

defaultContentLanguage = "en"

title = 'Casual Grinder Flash Fictions'

theme = "dream"

[params]

# backgroundImage = "https://images7.alphacoders.com/131/thumb-1920-1314311.jpg"

# backgroundImageDark = "https://images5.alphacoders.com/646/thumb-1920-646221.jpg"

lightTheme = "emerald"

darkTheme = "forest"

author = "Casual Grinder"

description = "Casual Grinder's Flash Fiction Collections"

headerTitle = "Casual Grinder Flash Fiction"

motto = "I take characters into deep waters and they discover themselves."

avatar = "https://lh3.googleusercontent.com/a/ACg8ocLJzFi_RnpI5Ew9tWSaMiTL4F85sR71_9tgf-VwQGoMqX1iYJ8=s576-c-no"

favicon = "https://lh3.googleusercontent.com/a/ACg8ocLJzFi_RnpI5Ew9tWSaMiTL4F85sR71_9tgf-VwQGoMqX1iYJ8=s576-c-no"

footerBottomText = "The Psalm In Darkness Project"

reorderNavItems = ["search", "categories", "tags"]

stickyNav = true

showTableOfContents = true

showSummaryCoverInPost = true

showPrevNextPost = true

# rss = true


# [services]

# [services.disqus]

# shortname = "casual"

# [markup]

# [markup.highlight]

# noClasses = false
